import type {
  User,
  SelfieLog,
  Facility,
  FacilityAuditor,
  UtilityAccount,
  UtilityTariff,
  UtilityBillingRecord,
  SolarPlant,
  SolarGenerationRecord,
  DGSet,
  DGAuditRecord,
  Transformer,
  TransformerAuditRecord,
  FanAuditRecord,
  LightingAuditRecord,
  LuxMeasurement,
  HVACAudit,
  MiscLoadAuditRecord,
  Pump,
  PumpAuditRecord,
} from "./dummy-types";

export const users: User[] = [
  {
    _id: "u1",
    name: "Ajit Kumar",
    email: "ajit.kumar@example.com",
    role: "admin",
    phone: "9876543210",
    status: "active",
    latestSelfieUrl: "https://dummycdn.com/selfies/u1-latest.jpg",
    lastSelfieAt: new Date("2026-03-17T09:10:00Z"),
    created_at: new Date("2026-01-01T10:00:00Z"),
    updated_at: new Date("2026-03-17T09:10:00Z"),
  },
  {
    _id: "u2",
    name: "Neha Sharma",
    email: "neha.sharma@example.com",
    role: "auditor",
    phone: "9811111111",
    status: "active",
    latestSelfieUrl: "https://dummycdn.com/selfies/u2-latest.jpg",
    lastSelfieAt: new Date("2026-03-16T08:45:00Z"),
    created_at: new Date("2026-01-05T11:00:00Z"),
    updated_at: new Date("2026-03-16T08:45:00Z"),
  },
  {
    _id: "u3",
    name: "Rohit Verma",
    email: "rohit.verma@example.com",
    role: "auditor",
    phone: "9822222222",
    status: "inactive",
    latestSelfieUrl: "https://dummycdn.com/selfies/u3-latest.jpg",
    lastSelfieAt: new Date("2026-03-10T07:30:00Z"),
    created_at: new Date("2026-01-10T09:30:00Z"),
    updated_at: new Date("2026-03-10T07:30:00Z"),
  },
];

export const selfie_logs: SelfieLog[] = [
  {
    _id: "sl1",
    userId: "u1",
    imageUrl: "https://dummycdn.com/selfies/u1-20260317-1.jpg",
    capturedAt: new Date("2026-03-17T09:10:00Z"),
    sessionId: "sess_u1_001",
    loginAt: new Date("2026-03-17T09:08:30Z"),
    createdAt: new Date("2026-03-17T09:10:05Z"),
  },
  {
    _id: "sl2",
    userId: "u2",
    imageUrl: "https://dummycdn.com/selfies/u2-20260316-1.jpg",
    capturedAt: new Date("2026-03-16T08:45:00Z"),
    sessionId: "sess_u2_001",
    loginAt: new Date("2026-03-16T08:44:10Z"),
    createdAt: new Date("2026-03-16T08:45:03Z"),
  },
  {
    _id: "sl3",
    userId: "u1",
    imageUrl: "https://dummycdn.com/selfies/u1-20260315-1.jpg",
    capturedAt: new Date("2026-03-15T09:02:00Z"),
    sessionId: "sess_u1_002",
    loginAt: new Date("2026-03-15T09:01:00Z"),
    createdAt: new Date("2026-03-15T09:02:02Z"),
  },
  {
    _id: "sl4",
    userId: "u3",
    imageUrl: "https://dummycdn.com/selfies/u3-20260310-1.jpg",
    capturedAt: new Date("2026-03-10T07:30:00Z"),
    sessionId: "sess_u3_001",
    loginAt: new Date("2026-03-10T07:28:40Z"),
    createdAt: new Date("2026-03-10T07:30:04Z"),
  },
];

export const facilities: Facility[] = [
  {
    _id: "f1",
    owner_user_id: "u1",
    name: "ABC Textile Mill",
    city: "Ludhiana",
    address: "Industrial Area Phase 1, Ludhiana, Punjab",
    client_representative: "Raj Singh",
    client_contact_number: "9780000001",
    client_email: "raj.singh@abctextile.com",
    facility_type: "Industrial",
    status: "active",
    created_by: "u1",
    created_at: new Date("2026-01-12T10:00:00Z").toLocaleDateString(),
    updated_at: new Date("2026-03-01T11:00:00Z").toLocaleDateString(),
  },
  {
    _id: "f2",
    owner_user_id: "u1",
    name: "Sunrise Hospital",
    city: "Amritsar",
    address: "Mall Road, Amritsar, Punjab",
    client_representative: "Dr. Meenakshi Arora",
    client_contact_number: "9780000002",
    client_email: "admin@sunrisehospital.com",
    facility_type: "Hospital",
    status: "active",
    created_by: "u1",
    created_at: new Date("2026-01-20T10:00:00Z"),
    updated_at: new Date("2026-03-02T10:30:00Z"),
  },
  {
    _id: "f3",
    owner_user_id: "u1",
    name: "Grand Residency Hotel",
    city: "Jalandhar",
    address: "GT Road, Jalandhar, Punjab",
    client_representative: "Karan Malhotra",
    client_contact_number: "9780000003",
    client_email: "gm@grandresidency.com",
    facility_type: "Hotel",
    status: "active",
    created_by: "u1",
    created_at: new Date("2026-02-01T09:00:00Z"),
    updated_at: new Date("2026-03-03T12:00:00Z"),
  },
];

export const facility_auditors: FacilityAuditor[] = [
  {
    _id: "fa1",
    facility_id: "f1",
    user_id: "u2",
    assigned_role: "lead_auditor",
    assigned_at: new Date("2026-02-01T09:00:00Z"),
    assigned_by: "u1",
  },
  {
    _id: "fa2",
    facility_id: "f1",
    user_id: "u3",
    assigned_role: "support_auditor",
    assigned_at: new Date("2026-02-01T09:15:00Z"),
    assigned_by: "u1",
  },
  {
    _id: "fa3",
    facility_id: "f2",
    user_id: "u2",
    assigned_role: "lead_auditor",
    assigned_at: new Date("2026-02-10T10:00:00Z"),
    assigned_by: "u1",
  },
  {
    _id: "fa4",
    facility_id: "f3",
    user_id: "u3",
    assigned_role: "lead_auditor",
    assigned_at: new Date("2026-02-15T11:00:00Z"),
    assigned_by: "u1",
  },
];

export const utility_accounts: UtilityAccount[] = [
  {
    _id: "ua1",
    facility_id: "f1",
    account_number: "PSPCL-IND-0001",
    connection_type: "HT",
    category: "Industrial",
    sanctioned_demand_kVA: 750,
    dataSheet: {
      solar: { connected: true, status: "pending" },
      dg: { connected: true, status: "pending" },
      transformer: { connected: true, status: "pending" },
      pump: { connected: true, status: "pending" },
      tariff: { connected: true, status: "pending" },
      billing: { connected: true, status: "pending" },
      hvac: { connected: true, status: "pending" },
      ac: { connected: true, status: "pending" },
      lighting: { connected: true, status: "pending" },
      fan: { connected: true, status: "pending" },
      lux: { connected: true, status: "pending" },
      misc: { connected: true, status: "pending" },
    },
    is_transformer_maintained_by_facility: true,
    is_active: true,
    created_at: new Date("2026-01-13T10:00:00Z"),
    updated_at: new Date("2026-03-01T10:00:00Z"),
  },
  {
    _id: "ua2",
    facility_id: "f2",
    account_number: "PSPCL-HOS-0002",
    connection_type: "HT",
    category: "Hospital",
    sanctioned_demand_kVA: 500,
    dataSheet: {
      solar: { connected: true, status: "pending" },
      dg: { connected: true, status: "pending" },
      transformer: { connected: true, status: "pending" },
      pump: { connected: true, status: "pending" },
      tariff: { connected: true, status: "pending" },
      billing: { connected: true, status: "pending" },
      hvac: { connected: true, status: "pending" },
      ac: { connected: true, status: "pending" },
      lighting: { connected: true, status: "pending" },
      fan: { connected: true, status: "pending" },
      lux: { connected: true, status: "pending" },
      misc: { connected: true, status: "pending" },
    },
    is_transformer_maintained_by_facility: true,
    is_active: true,
    created_at: new Date("2026-01-21T10:00:00Z"),
    updated_at: new Date("2026-03-02T10:00:00Z"),
  },
  {
    _id: "ua3",
    facility_id: "f3",
    account_number: "PSPCL-HOT-0003",
    connection_type: "LT",
    category: "Hotel",
    sanctioned_demand_kVA: 250,
    dataSheet: {
      solar: { connected: true, status: "pending" },
      dg: { connected: true, status: "pending" },
      transformer: { connected: true, status: "pending" },
      pump: { connected: true, status: "pending" },
      tariff: { connected: true, status: "pending" },
      billing: { connected: true, status: "pending" },
      hvac: { connected: true, status: "pending" },
      ac: { connected: true, status: "pending" },
      lighting: { connected: true, status: "pending" },
      fan: { connected: true, status: "pending" },
      lux: { connected: true, status: "pending" },
      misc: { connected: true, status: "pending" },
    },
    is_transformer_maintained_by_facility: true,
    is_active: true,
    created_at: new Date("2026-02-02T10:00:00Z"),
    updated_at: new Date("2026-03-03T10:00:00Z"),
  },
];

export const utility_tariffs: UtilityTariff[] = [
  {
    _id: "ut1",
    utility_account_id: "ua1",
    effective_from: new Date("2026-01-01"),
    effective_to: null,
    basic_energy_charges_rs_per_unit: 7.8,
    fixed_charges_rs_per_kW_or_per_kVA: 320,
    ed_percent: 5,
    octroi_rs_per_unit: 0.15,
    surcharge_rs: 1200,
    cow_cess_rs: 180,
    rental_rs: 300,
    infracess_rs: 90,
    other_charges_or_rebates_rs: -500,
    any_other_rs: 100,
    created_at: new Date("2026-01-01T00:00:00Z"),
    updated_at: new Date("2026-03-01T00:00:00Z"),
  },
  {
    _id: "ut2",
    utility_account_id: "ua2",
    effective_from: new Date("2026-01-01"),
    effective_to: null,
    basic_energy_charges_rs_per_unit: 8.2,
    fixed_charges_rs_per_kW_or_per_kVA: 350,
    ed_percent: 5,
    octroi_rs_per_unit: 0.18,
    surcharge_rs: 1500,
    cow_cess_rs: 220,
    rental_rs: 350,
    infracess_rs: 110,
    other_charges_or_rebates_rs: 0,
    any_other_rs: 75,
    created_at: new Date("2026-01-01T00:00:00Z"),
    updated_at: new Date("2026-03-02T00:00:00Z"),
  },
  {
    _id: "ut3",
    utility_account_id: "ua3",
    effective_from: new Date("2026-01-01"),
    effective_to: null,
    basic_energy_charges_rs_per_unit: 7.2,
    fixed_charges_rs_per_kW_or_per_kVA: 280,
    ed_percent: 5,
    octroi_rs_per_unit: 0.12,
    surcharge_rs: 900,
    cow_cess_rs: 120,
    rental_rs: 200,
    infracess_rs: 60,
    other_charges_or_rebates_rs: -250,
    any_other_rs: 50,
    created_at: new Date("2026-01-01T00:00:00Z"),
    updated_at: new Date("2026-03-03T00:00:00Z"),
  },
];

export const utility_billing_records: UtilityBillingRecord[] = [
  {
    _id: "ubr1",
    utility_account_id: "ua1",
    billing_period_start: new Date("2026-02-01"),
    billing_period_end: new Date("2026-02-28"),
    billing_days: 28,
    bill_no: "BILL-UA1-FEB",
    mdi_kVA: 690,
    units_kWh: 81200,
    units_kVAh: 84500,
    pf: 0.96,
    fixed_charges_rs: 240000,
    energy_charges_rs: 633360,
    taxes_and_rent_rs: 38500,
    other_charges_rs: 6200,
    monthly_electricity_bill_rs: 918060,
    unit_consumption_per_day_kVAh: 3017.86,
    average_per_unit_cost_rs: 10.86,
    created_at: new Date("2026-03-01T09:00:00Z"),
    updated_at: new Date("2026-03-01T09:00:00Z"),
  },
  {
    _id: "ubr2",
    utility_account_id: "ua2",
    billing_period_start: new Date("2026-02-01"),
    billing_period_end: new Date("2026-02-28"),
    billing_days: 28,
    bill_no: "BILL-UA2-FEB",
    mdi_kVA: 455,
    units_kWh: 56200,
    units_kVAh: 58400,
    pf: 0.97,
    fixed_charges_rs: 175000,
    energy_charges_rs: 460840,
    taxes_and_rent_rs: 29000,
    other_charges_rs: 4800,
    monthly_electricity_bill_rs: 669640,
    unit_consumption_per_day_kVAh: 2085.71,
    average_per_unit_cost_rs: 11.47,
    created_at: new Date("2026-03-02T09:00:00Z"),
    updated_at: new Date("2026-03-02T09:00:00Z"),
  },
  {
    _id: "ubr3",
    utility_account_id: "ua3",
    billing_period_start: new Date("2026-02-01"),
    billing_period_end: new Date("2026-02-28"),
    billing_days: 28,
    bill_no: "BILL-UA3-FEB",
    mdi_kVA: 225,
    units_kWh: 28400,
    units_kVAh: 29850,
    pf: 0.95,
    fixed_charges_rs: 70000,
    energy_charges_rs: 204480,
    taxes_and_rent_rs: 13500,
    other_charges_rs: 2500,
    monthly_electricity_bill_rs: 290480,
    unit_consumption_per_day_kVAh: 1066.07,
    average_per_unit_cost_rs: 9.73,
    created_at: new Date("2026-03-03T09:00:00Z"),
    updated_at: new Date("2026-03-03T09:00:00Z"),
  },
];

export const solar_plants: SolarPlant[] = [
  {
    _id: "sp1",
    facility_id: "f1",
    utility_account_id: "ua1",
    plant_name: "ABC Rooftop Solar Plant",
    rating_kWp: 300,
    panel_rating_watt: 540,
    no_of_panels: 556,
    inverter_make: "Sungrow",
    inverter_rating_kW: 250,
    created_at: new Date("2026-01-15T10:00:00Z"),
    updated_at: new Date("2026-03-01T10:00:00Z"),
  },
  {
    _id: "sp2",
    facility_id: "f2",
    utility_account_id: "ua2",
    plant_name: "Hospital Block Solar",
    rating_kWp: 180,
    panel_rating_watt: 550,
    no_of_panels: 328,
    inverter_make: "Growatt",
    inverter_rating_kW: 150,
    created_at: new Date("2026-01-25T10:00:00Z"),
    updated_at: new Date("2026-03-02T10:00:00Z"),
  },
];

export const solar_generation_records: SolarGenerationRecord[] = [
  {
    _id: "sgr1",
    solar_plant_id: "sp1",
    utility_account_id: "ua1",
    billing_period_start: new Date("2026-02-01"),
    billing_period_end: new Date("2026-02-28"),
    billing_days: 28,
    bill_no: "SOL-UA1-FEB",
    import_kWh: 41200,
    import_kVAh: 42500,
    import_kVA: 620,
    export_kWh: 18500,
    export_kVAh: 19100,
    export_kVA: 280,
    net_kWh: 22700,
    net_kVAh: 23400,
    net_kVA: 340,
    solar_generation_kWh: 39200,
    solar_generation_kVAh: 40100,
    solar_generation_kVA: 590,
    created_at: new Date("2026-03-01T10:30:00Z"),
    updated_at: new Date("2026-03-01T10:30:00Z"),
  },
  {
    _id: "sgr2",
    solar_plant_id: "sp2",
    utility_account_id: "ua2",
    billing_period_start: new Date("2026-02-01"),
    billing_period_end: new Date("2026-02-28"),
    billing_days: 28,
    bill_no: "SOL-UA2-FEB",
    import_kWh: 29800,
    import_kVAh: 30600,
    import_kVA: 410,
    export_kWh: 9100,
    export_kVAh: 9400,
    export_kVA: 130,
    net_kWh: 20700,
    net_kVAh: 21200,
    net_kVA: 280,
    solar_generation_kWh: 22400,
    solar_generation_kVAh: 22900,
    solar_generation_kVA: 315,
    created_at: new Date("2026-03-02T10:30:00Z"),
    updated_at: new Date("2026-03-02T10:30:00Z"),
  },
];

export const dg_sets: DGSet[] = [
  {
    _id: "dg1",
    facility_id: "f1",
    utility_account_id: "ua1",
    dg_number: "DG-1",
    make_model: "Kirloskar KG1-500",
    year_of_installation: 2021,
    rated_capacity_kVA: 500,
    rated_active_power_kW: 400,
    rated_voltage_V: 415,
    rated_speed_RPM: 1500,
    fuel_type: "Diesel",
    created_at: new Date("2026-01-16T09:00:00Z"),
    updated_at: new Date("2026-03-01T11:00:00Z"),
  },
  {
    _id: "dg2",
    facility_id: "f2",
    utility_account_id: "ua2",
    dg_number: "DG-2",
    make_model: "Cummins C550D5",
    year_of_installation: 2020,
    rated_capacity_kVA: 550,
    rated_active_power_kW: 440,
    rated_voltage_V: 415,
    rated_speed_RPM: 1500,
    fuel_type: "Diesel",
    created_at: new Date("2026-01-26T09:00:00Z"),
    updated_at: new Date("2026-03-02T11:00:00Z"),
  },
  {
    _id: "dg3",
    facility_id: "f3",
    utility_account_id: "ua3",
    dg_number: "DG-3",
    make_model: "Mahindra Powerol 250",
    year_of_installation: 2019,
    rated_capacity_kVA: 250,
    rated_active_power_kW: 200,
    rated_voltage_V: 415,
    rated_speed_RPM: 1500,
    fuel_type: "Diesel",
    created_at: new Date("2026-02-03T09:00:00Z"),
    updated_at: new Date("2026-03-03T11:00:00Z"),
  },
];

export const dg_audit_records: DGAuditRecord[] = [
  {
    _id: "dga1",
    dg_set_id: "dg1",
    utility_account_id: "ua1",
    measured_voltage_LL: 414,
    measured_current_avg: 558,
    measured_kW_output: 348,
    measured_kVA_output: 386,
    power_factor: 0.9,
    frequency_Hz: 49.9,
    max_load_observed_kW: 372,
    min_load_observed_kW: 180,
    average_loading_percent: 87,
    load_factor_percent: 68,
    idle_running_observed: true,
    parallel_operation: false,
    annual_fuel_consumption_liters: 48200,
    units_generated_per_year_kWh: 180500,
    total_working_hours_per_year: 920,
    units_generated_per_hour_kWh: 196.2,
    fuel_consumption_per_hour_liters: 52.4,
    fuel_consumption_during_test_lph: 51.1,
    units_generated_during_test_kWh: 192.5,
    specific_fuel_consumption_l_per_kWh: 0.266,
    manufacturer_sfc_l_per_kWh: 0.25,
    sfc_deviation_percent: 6.4,
    fuel_cost_rs_per_liter: 91,
    annual_fuel_cost_rs: 4386200,
    dg_cost_per_kWh_rs: 24.3,
    grid_cost_per_kWh_rs: 10.8,
    calculated_efficiency_percent: 34,
    manufacturer_efficiency_percent: 37,
    efficiency_deviation_percent: -8.11,
    exhaust_temperature_C: 385,
    cooling_water_temperature_C: 82,
    lube_oil_pressure_bar: 4.5,
    lube_oil_consumption_liters_per_year: 180,
    total_operating_hours: 920,
    hours_since_last_overhaul: 2200,
    air_fuel_filter_condition: "Good",
    visible_smoke_or_abnormal_vibration: false,
    created_at: new Date("2026-03-01T12:00:00Z"),
    updated_at: new Date("2026-03-01T12:00:00Z"),
  },
  {
    _id: "dga2",
    dg_set_id: "dg2",
    utility_account_id: "ua2",
    measured_voltage_LL: 416,
    measured_current_avg: 610,
    measured_kW_output: 390,
    measured_kVA_output: 430,
    power_factor: 0.91,
    frequency_Hz: 50.1,
    max_load_observed_kW: 420,
    min_load_observed_kW: 220,
    average_loading_percent: 88.6,
    load_factor_percent: 70,
    idle_running_observed: false,
    parallel_operation: false,
    annual_fuel_consumption_liters: 52500,
    units_generated_per_year_kWh: 205000,
    total_working_hours_per_year: 980,
    units_generated_per_hour_kWh: 209.18,
    fuel_consumption_per_hour_liters: 53.57,
    fuel_consumption_during_test_lph: 52.8,
    units_generated_during_test_kWh: 205.4,
    specific_fuel_consumption_l_per_kWh: 0.257,
    manufacturer_sfc_l_per_kWh: 0.245,
    sfc_deviation_percent: 4.9,
    fuel_cost_rs_per_liter: 91,
    annual_fuel_cost_rs: 4777500,
    dg_cost_per_kWh_rs: 23.3,
    grid_cost_per_kWh_rs: 11.2,
    calculated_efficiency_percent: 35,
    manufacturer_efficiency_percent: 38,
    efficiency_deviation_percent: -7.89,
    exhaust_temperature_C: 392,
    cooling_water_temperature_C: 84,
    lube_oil_pressure_bar: 4.7,
    lube_oil_consumption_liters_per_year: 210,
    total_operating_hours: 980,
    hours_since_last_overhaul: 1800,
    air_fuel_filter_condition: "Fair",
    visible_smoke_or_abnormal_vibration: false,
    created_at: new Date("2026-03-02T12:00:00Z"),
    updated_at: new Date("2026-03-02T12:00:00Z"),
  },
  {
    _id: "dga3",
    dg_set_id: "dg3",
    utility_account_id: "ua3",
    measured_voltage_LL: 413,
    measured_current_avg: 290,
    measured_kW_output: 176,
    measured_kVA_output: 195,
    power_factor: 0.9,
    frequency_Hz: 49.8,
    max_load_observed_kW: 190,
    min_load_observed_kW: 95,
    average_loading_percent: 88,
    load_factor_percent: 64,
    idle_running_observed: true,
    parallel_operation: false,
    annual_fuel_consumption_liters: 21800,
    units_generated_per_year_kWh: 83500,
    total_working_hours_per_year: 540,
    units_generated_per_hour_kWh: 154.63,
    fuel_consumption_per_hour_liters: 40.37,
    fuel_consumption_during_test_lph: 39.6,
    units_generated_during_test_kWh: 151.8,
    specific_fuel_consumption_l_per_kWh: 0.261,
    manufacturer_sfc_l_per_kWh: 0.248,
    sfc_deviation_percent: 5.24,
    fuel_cost_rs_per_liter: 91,
    annual_fuel_cost_rs: 1983800,
    dg_cost_per_kWh_rs: 23.76,
    grid_cost_per_kWh_rs: 9.8,
    calculated_efficiency_percent: 33,
    manufacturer_efficiency_percent: 36,
    efficiency_deviation_percent: -8.33,
    exhaust_temperature_C: 378,
    cooling_water_temperature_C: 80,
    lube_oil_pressure_bar: 4.2,
    lube_oil_consumption_liters_per_year: 95,
    total_operating_hours: 540,
    hours_since_last_overhaul: 2600,
    air_fuel_filter_condition: "Good",
    visible_smoke_or_abnormal_vibration: true,
    created_at: new Date("2026-03-03T12:00:00Z"),
    updated_at: new Date("2026-03-03T12:00:00Z"),
  },
];

export const transformers: Transformer[] = [
  {
    _id: "tr1",
    facility_id: "f1",
    utility_account_id: "ua1",
    transformer_tag: "TR-ABC-1",
    rated_capacity_kVA: 1000,
    type_of_cooling: "ONAN",
    rated_HV_kV: 11,
    rated_LV_V: 433,
    rated_HV_current_A: 52.5,
    rated_LV_current_A: 1333,
    no_load_loss_kW: 1.8,
    full_load_loss_kW: 11.5,
    nameplate_efficiency_percent: 98.4,
    created_at: new Date("2026-01-16T10:00:00Z"),
    updated_at: new Date("2026-03-01T10:00:00Z"),
  },
  {
    _id: "tr2",
    facility_id: "f2",
    utility_account_id: "ua2",
    transformer_tag: "TR-HOS-1",
    rated_capacity_kVA: 630,
    type_of_cooling: "ONAN",
    rated_HV_kV: 11,
    rated_LV_V: 433,
    rated_HV_current_A: 33.1,
    rated_LV_current_A: 840,
    no_load_loss_kW: 1.2,
    full_load_loss_kW: 8.2,
    nameplate_efficiency_percent: 98.1,
    created_at: new Date("2026-01-26T10:00:00Z"),
    updated_at: new Date("2026-03-02T10:00:00Z"),
  },
];

export const transformer_audit_records: TransformerAuditRecord[] = [
  {
    _id: "tar1",
    transformer_id: "tr1",
    utility_account_id: "ua1",
    total_losses_kW: 8.9,
    average_load_kVA: 640,
    percent_loading: 64,
    max_load_kVA: 790,
    load_factor_percent: 72,
    operating_hours_per_year: 7800,
    annual_energy_supplied_kWh: 4980000,
    annual_energy_losses_kWh: 69420,
    per_unit_cost_rs: 10.6,
    cost_of_losses_rs: 735852,
    power_factor_LT: 0.97,
    harmonics_THD_percent: 4.2,
    neutral_earth_resistance_ohms: 0.8,
    body_to_earth_resistance_ohms: 1.1,
    silica_gel_cobalt_type: "Blue-Pink",
    silica_gel_non_cobalt_type: "N/A",
    oil_level: "Normal",
    line_voltage_Vr: 433,
    line_voltage_Vy: 431,
    line_voltage_Vb: 434,
    phase_voltage_Vr_n: 250,
    phase_voltage_Vy_n: 249,
    phase_voltage_Vb_n: 251,
    line_current_Ir: 890,
    line_current_Iy: 875,
    line_current_Ib: 902,
    created_at: new Date("2026-03-01T13:00:00Z"),
    updated_at: new Date("2026-03-01T13:00:00Z"),
  },
  {
    _id: "tar2",
    transformer_id: "tr2",
    utility_account_id: "ua2",
    total_losses_kW: 6.4,
    average_load_kVA: 410,
    percent_loading: 65.08,
    max_load_kVA: 520,
    load_factor_percent: 70,
    operating_hours_per_year: 8200,
    annual_energy_supplied_kWh: 3362000,
    annual_energy_losses_kWh: 52480,
    per_unit_cost_rs: 11.4,
    cost_of_losses_rs: 598272,
    power_factor_LT: 0.98,
    harmonics_THD_percent: 3.9,
    neutral_earth_resistance_ohms: 0.7,
    body_to_earth_resistance_ohms: 0.9,
    silica_gel_cobalt_type: "Blue",
    silica_gel_non_cobalt_type: "N/A",
    oil_level: "Slightly Low",
    line_voltage_Vr: 432,
    line_voltage_Vy: 433,
    line_voltage_Vb: 431,
    phase_voltage_Vr_n: 249,
    phase_voltage_Vy_n: 250,
    phase_voltage_Vb_n: 248,
    line_current_Ir: 602,
    line_current_Iy: 595,
    line_current_Ib: 608,
    created_at: new Date("2026-03-02T13:00:00Z"),
    updated_at: new Date("2026-03-02T13:00:00Z"),
  },
];

export const fan_audit_records: FanAuditRecord[] = [
  {
    _id: "fan1",
    utility_account_id: "ua1",
    building_block: "Production Block A",
    area_location: "Weaving Section",
    fan_type: "Ceiling Fan",
    make_model: "Crompton Energy Saver",
    rated_power_W: 75,
    measured_power_W: 68,
    quantity_nos: 42,
    speed_control_type: "Regulator",
    operating_hours_per_day: 16,
    operating_days_per_year: 300,
    loading_factor_percent: 90,
    connected_load_kW: 3.15,
    annual_energy_consumption_kWh: 13608,
    condition: "Good",
    remarks: "Most fans are in good condition",
    created_at: new Date("2026-03-01T14:00:00Z"),
    updated_at: new Date("2026-03-01T14:00:00Z"),
  },
  {
    _id: "fan2",
    utility_account_id: "ua2",
    building_block: "Ward Block",
    area_location: "Patient Rooms",
    fan_type: "Wall Fan",
    make_model: "Havells Swing",
    rated_power_W: 60,
    measured_power_W: 58,
    quantity_nos: 35,
    speed_control_type: "3-Step",
    operating_hours_per_day: 20,
    operating_days_per_year: 365,
    loading_factor_percent: 85,
    connected_load_kW: 2.1,
    annual_energy_consumption_kWh: 14819,
    condition: "Fair",
    remarks: "Some fans need cleaning",
    created_at: new Date("2026-03-02T14:00:00Z"),
    updated_at: new Date("2026-03-02T14:00:00Z"),
  },
  {
    _id: "fan3",
    utility_account_id: "ua3",
    building_block: "Guest Wing",
    area_location: "Lobby",
    fan_type: "Pedestal Fan",
    make_model: "Usha Maxx Air",
    rated_power_W: 55,
    measured_power_W: 52,
    quantity_nos: 12,
    speed_control_type: "Variable",
    operating_hours_per_day: 14,
    operating_days_per_year: 330,
    loading_factor_percent: 80,
    connected_load_kW: 0.66,
    annual_energy_consumption_kWh: 2882.88,
    condition: "Good",
    remarks: "Used mostly in peak season",
    created_at: new Date("2026-03-03T14:00:00Z"),
    updated_at: new Date("2026-03-03T14:00:00Z"),
  },
];

export const lighting_audit_records: LightingAuditRecord[] = [
  {
    _id: "lar1",
    utility_account_id: "ua1",
    area_location: "Production Floor",
    fixture_type: "LED Batten",
    lamp_type: "LED",
    wattage_W: 20,
    quantity_nos: 180,
    control_type: "Manual Switch",
    working_hours_per_day: 16,
    working_days_per_year: 300,
    connected_load_kW: 3.6,
    annual_energy_kWh: 17280,
    remarks: "Can be grouped with occupancy controls",
    created_at: new Date("2026-03-01T15:00:00Z"),
    updated_at: new Date("2026-03-01T15:00:00Z"),
  },
  {
    _id: "lar2",
    utility_account_id: "ua2",
    area_location: "Operation Theatre Corridor",
    fixture_type: "LED Panel",
    lamp_type: "LED",
    wattage_W: 36,
    quantity_nos: 90,
    control_type: "Sensor + Manual",
    working_hours_per_day: 24,
    working_days_per_year: 365,
    connected_load_kW: 3.24,
    annual_energy_kWh: 28382.4,
    remarks: "Critical area lighting",
    created_at: new Date("2026-03-02T15:00:00Z"),
    updated_at: new Date("2026-03-02T15:00:00Z"),
  },
  {
    _id: "lar3",
    utility_account_id: "ua3",
    area_location: "Banquet Hall",
    fixture_type: "Downlight",
    lamp_type: "LED",
    wattage_W: 12,
    quantity_nos: 140,
    control_type: "Dimmer",
    working_hours_per_day: 8,
    working_days_per_year: 280,
    connected_load_kW: 1.68,
    annual_energy_kWh: 3763.2,
    remarks: "Dimming used during events",
    created_at: new Date("2026-03-03T15:00:00Z"),
    updated_at: new Date("2026-03-03T15:00:00Z"),
  },
];

export const lux_measurements: LuxMeasurement[] = [
  {
    _id: "lux1",
    utility_account_id: "ua1",
    area_location: "Quality Inspection Room",
    room_type: "Inspection",
    required_lux: 500,
    measured_lux_point_1: 472,
    measured_lux_point_2: 488,
    measured_lux_point_3: 481,
    average_lux: 480.33,
    compliance: false,
    remarks: "Slightly below required level",
    created_at: new Date("2026-03-01T16:00:00Z"),
    updated_at: new Date("2026-03-01T16:00:00Z"),
  },
  {
    _id: "lux2",
    utility_account_id: "ua2",
    area_location: "Nurse Station",
    room_type: "Healthcare Work Area",
    required_lux: 300,
    measured_lux_point_1: 322,
    measured_lux_point_2: 330,
    measured_lux_point_3: 318,
    average_lux: 323.33,
    compliance: true,
    remarks: "Compliant",
    created_at: new Date("2026-03-02T16:00:00Z"),
    updated_at: new Date("2026-03-02T16:00:00Z"),
  },
  {
    _id: "lux3",
    utility_account_id: "ua3",
    area_location: "Reception",
    room_type: "Lobby",
    required_lux: 200,
    measured_lux_point_1: 190,
    measured_lux_point_2: 205,
    measured_lux_point_3: 198,
    average_lux: 197.67,
    compliance: false,
    remarks: "Add task lighting near desk",
    created_at: new Date("2026-03-03T16:00:00Z"),
    updated_at: new Date("2026-03-03T16:00:00Z"),
  },
];

export const hvac_audits: HVACAudit[] = [
  {
    _id: "hvac1",
    utility_account_id: "ua1",
    pre_audit_information: {
      facility_name: "ABC Textile Mill",
      location_address: "Industrial Area Phase 1, Ludhiana, Punjab",
      client_contact_person: "Raj Singh",
      contact_number_email: "9780000001 / raj.singh@abctextile.com",
      type_of_facility: "Industrial",
      audit_dates: [new Date("2026-03-01"), new Date("2026-03-02")],
      auditor_team_members_names: ["Neha Sharma", "Rohit Verma"],
      total_operating_hours_per_day: 20,
      hvac_operating_hours_per_day: 16,
      season_ambient_conditions: "Warm and dry",
    },
    documents_records_to_collect: {
      single_line_diagram_electrical: {
        available: true,
        remarks: "Latest revision available",
      },
      hvac_layout_piping_drawing: {
        available: true,
        remarks: "Chiller layout drawing shared",
      },
      chiller_operation_maintenance_log: {
        available: true,
        remarks: "Monthly maintenance log available",
      },
      water_treatment_records: {
        available: false,
        remarks: "To be collected from vendor",
      },
      cooling_tower_maintenance_record: {
        available: true,
        remarks: "Manual logbook available",
      },
      hvac_equipment_capacity_list: {
        available: true,
        remarks: "List verified with nameplates",
      },
      bms_setpoints_schedule: {
        available: false,
        remarks: "Facility does not use full BMS",
      },
    },
    hvac_equipment_register: [
      {
        equipment_name: "Chiller-1",
        equipment_type: "Water Cooled Chiller",
        make_model: "Carrier 250TR",
        rated_capacity_TR: 250,
        rated_power_kW: 180,
        year_of_installation: 2021,
        remarks: "Main production chiller",
      },
      {
        equipment_name: "Cooling Tower-1",
        equipment_type: "Cooling Tower",
        make_model: "Paharpur CT-01",
        rated_capacity_TR: 300,
        rated_power_kW: 15,
        year_of_installation: 2021,
        remarks: "Serving Chiller-1",
      },
    ],
    chiller_field_test: {
      readings: [
        {
          chilled_water_inlet_temp_C: 14.2,
          chilled_water_outlet_temp_C: 7.1,
          condenser_water_inlet_temp_C: 29.5,
          condenser_water_outlet_temp_C: 34.1,
          flow_rate_m3_per_hr: 112,
          power_input_kW: 168,
          cooling_produced_TR: 228,
        },
        {
          chilled_water_inlet_temp_C: 14.0,
          chilled_water_outlet_temp_C: 7.0,
          condenser_water_inlet_temp_C: 29.8,
          condenser_water_outlet_temp_C: 34.4,
          flow_rate_m3_per_hr: 110,
          power_input_kW: 170,
          cooling_produced_TR: 225,
        },
        {
          chilled_water_inlet_temp_C: 14.4,
          chilled_water_outlet_temp_C: 7.3,
          condenser_water_inlet_temp_C: 29.4,
          condenser_water_outlet_temp_C: 34.0,
          flow_rate_m3_per_hr: 113,
          power_input_kW: 169,
          cooling_produced_TR: 229,
        },
      ],
      average: {
        chilled_water_inlet_temp_C: 14.2,
        chilled_water_outlet_temp_C: 7.13,
        condenser_water_inlet_temp_C: 29.57,
        condenser_water_outlet_temp_C: 34.17,
        flow_rate_m3_per_hr: 111.67,
        power_input_kW: 169,
        cooling_produced_TR: 227.33,
      },
    },
    auxiliary_power: {
      components: [
        { component_name: "CHW Pump", power_kW: 18.5 },
        { component_name: "CDW Pump", power_kW: 22 },
        { component_name: "Cooling Tower Fan", power_kW: 15 },
      ],
      total_auxiliary_power_used_kW: 55.5,
    },
    cooling_tower_quick_test: {
      readings: [
        {
          hot_water_temp_C: 34.2,
          cold_water_temp_C: 29.4,
          wet_bulb_temp_C: 25.1,
          approach_C: 4.3,
          range_C: 4.8,
        },
        {
          hot_water_temp_C: 34.0,
          cold_water_temp_C: 29.2,
          wet_bulb_temp_C: 25.0,
          approach_C: 4.2,
          range_C: 4.8,
        },
        {
          hot_water_temp_C: 34.3,
          cold_water_temp_C: 29.5,
          wet_bulb_temp_C: 25.2,
          approach_C: 4.3,
          range_C: 4.8,
        },
      ],
      average: {
        hot_water_temp_C: 34.17,
        cold_water_temp_C: 29.37,
        wet_bulb_temp_C: 25.1,
        approach_C: 4.27,
        range_C: 4.8,
      },
    },
    summary: {
      average_cooling_produced_TR: 227.33,
      average_chiller_power_used_kW: 169,
      total_auxiliary_power_used_kW: 55.5,
      total_plant_power_kW: 224.5,
      plant_efficiency_kW_per_TR: 0.99,
      coefficient_of_performance: 3.54,
    },
    created_at: new Date("2026-03-02T17:00:00Z"),
    updated_at: new Date("2026-03-02T17:00:00Z"),
  },
  {
    _id: "hvac2",
    utility_account_id: "ua2",
    pre_audit_information: {
      facility_name: "Sunrise Hospital",
      location_address: "Mall Road, Amritsar, Punjab",
      client_contact_person: "Dr. Meenakshi Arora",
      contact_number_email: "9780000002 / admin@sunrisehospital.com",
      type_of_facility: "Hospital",
      audit_dates: [new Date("2026-03-05"), new Date("2026-03-06")],
      auditor_team_members_names: ["Neha Sharma"],
      total_operating_hours_per_day: 24,
      hvac_operating_hours_per_day: 24,
      season_ambient_conditions: "Mild weather, moderate humidity",
    },
    documents_records_to_collect: {
      single_line_diagram_electrical: {
        available: true,
        remarks: "Approved electrical drawing available",
      },
      hvac_layout_piping_drawing: {
        available: true,
        remarks: "AHU and chilled water piping drawing available",
      },
      chiller_operation_maintenance_log: {
        available: true,
        remarks: "Digital records maintained",
      },
      water_treatment_records: {
        available: true,
        remarks: "Monthly testing reports available",
      },
      cooling_tower_maintenance_record: {
        available: true,
        remarks: "Available with maintenance supervisor",
      },
      hvac_equipment_capacity_list: {
        available: true,
        remarks: "Equipment inventory updated",
      },
      bms_setpoints_schedule: {
        available: true,
        remarks: "BMS screenshots shared",
      },
    },
    hvac_equipment_register: [
      {
        equipment_name: "Chiller-A",
        equipment_type: "Air Cooled Chiller",
        make_model: "Daikin 180TR",
        rated_capacity_TR: 180,
        rated_power_kW: 145,
        year_of_installation: 2022,
        remarks: "Serves ICU and OT blocks",
      },
      {
        equipment_name: "AHU-OT-1",
        equipment_type: "AHU",
        make_model: "Blue Star AHU",
        rated_capacity_TR: 25,
        rated_power_kW: 5.5,
        year_of_installation: 2022,
        remarks: "Operation theatre AHU",
      },
    ],
    chiller_field_test: {
      readings: [
        {
          chilled_water_inlet_temp_C: 13.6,
          chilled_water_outlet_temp_C: 6.9,
          condenser_water_inlet_temp_C: 0,
          condenser_water_outlet_temp_C: 0,
          flow_rate_m3_per_hr: 86,
          power_input_kW: 138,
          cooling_produced_TR: 170,
        },
        {
          chilled_water_inlet_temp_C: 13.7,
          chilled_water_outlet_temp_C: 7.0,
          condenser_water_inlet_temp_C: 0,
          condenser_water_outlet_temp_C: 0,
          flow_rate_m3_per_hr: 87,
          power_input_kW: 139,
          cooling_produced_TR: 171,
        },
        {
          chilled_water_inlet_temp_C: 13.5,
          chilled_water_outlet_temp_C: 6.8,
          condenser_water_inlet_temp_C: 0,
          condenser_water_outlet_temp_C: 0,
          flow_rate_m3_per_hr: 85,
          power_input_kW: 137,
          cooling_produced_TR: 168,
        },
      ],
      average: {
        chilled_water_inlet_temp_C: 13.6,
        chilled_water_outlet_temp_C: 6.9,
        condenser_water_inlet_temp_C: 0,
        condenser_water_outlet_temp_C: 0,
        flow_rate_m3_per_hr: 86,
        power_input_kW: 138,
        cooling_produced_TR: 169.67,
      },
    },
    auxiliary_power: {
      components: [
        { component_name: "Primary Pump", power_kW: 14 },
        { component_name: "Secondary Pump", power_kW: 12 },
        { component_name: "AHU Fans", power_kW: 21 },
      ],
      total_auxiliary_power_used_kW: 47,
    },
    cooling_tower_quick_test: {
      readings: [
        {
          hot_water_temp_C: 0,
          cold_water_temp_C: 0,
          wet_bulb_temp_C: 0,
          approach_C: 0,
          range_C: 0,
        },
      ],
      average: {
        hot_water_temp_C: 0,
        cold_water_temp_C: 0,
        wet_bulb_temp_C: 0,
        approach_C: 0,
        range_C: 0,
      },
    },
    summary: {
      average_cooling_produced_TR: 169.67,
      average_chiller_power_used_kW: 138,
      total_auxiliary_power_used_kW: 47,
      total_plant_power_kW: 185,
      plant_efficiency_kW_per_TR: 1.09,
      coefficient_of_performance: 3.34,
    },
    created_at: new Date("2026-03-06T17:00:00Z"),
    updated_at: new Date("2026-03-06T17:00:00Z"),
  },
];

export const misc_load_audit_records: MiscLoadAuditRecord[] = [
  {
    _id: "misc1",
    utility_account_id: "ua1",
    equipment_name: "Air Compressor",
    category: "Compressed Air",
    location_department: "Utility Room",
    quantity: 2,
    rated_power_kW: 37,
    average_operating_hours_per_day: 14,
    operating_days_per_year: 300,
    load_factor_percent: 78,
    estimated_annual_energy_kWh: 242424,
    created_at: new Date("2026-03-01T18:00:00Z"),
    updated_at: new Date("2026-03-01T18:00:00Z"),
  },
  {
    _id: "misc2",
    utility_account_id: "ua2",
    equipment_name: "Sterilizer",
    category: "Medical Equipment",
    location_department: "CSSD",
    quantity: 3,
    rated_power_kW: 12,
    average_operating_hours_per_day: 8,
    operating_days_per_year: 365,
    load_factor_percent: 70,
    estimated_annual_energy_kWh: 73584,
    created_at: new Date("2026-03-02T18:00:00Z"),
    updated_at: new Date("2026-03-02T18:00:00Z"),
  },
  {
    _id: "misc3",
    utility_account_id: "ua3",
    equipment_name: "Kitchen Oven",
    category: "Kitchen Load",
    location_department: "Main Kitchen",
    quantity: 2,
    rated_power_kW: 18,
    average_operating_hours_per_day: 6,
    operating_days_per_year: 330,
    load_factor_percent: 65,
    estimated_annual_energy_kWh: 46332,
    created_at: new Date("2026-03-03T18:00:00Z"),
    updated_at: new Date("2026-03-03T18:00:00Z"),
  },
];

export const pumps: Pump[] = [
  {
    _id: "p1",
    facility_id: "f1",
    utility_account_id: "ua1",
    pump_tag_number: "P-ABC-1",
    make_model: "Kirloskar End Suction",
    rated_power_kW_or_HP: 15,
    rated_flow_m3_per_hr: 60,
    rated_head_m: 28,
    rated_speed_RPM: 2900,
    number_of_stages: 1,
    year_of_installation: 2021,
    created_at: new Date("2026-01-17T10:00:00Z"),
    updated_at: new Date("2026-03-01T10:00:00Z"),
  },
  {
    _id: "p2",
    facility_id: "f2",
    utility_account_id: "ua2",
    pump_tag_number: "P-HOS-1",
    make_model: "Grundfos Vertical Pump",
    rated_power_kW_or_HP: 10,
    rated_flow_m3_per_hr: 42,
    rated_head_m: 32,
    rated_speed_RPM: 2900,
    number_of_stages: 4,
    year_of_installation: 2022,
    created_at: new Date("2026-01-27T10:00:00Z"),
    updated_at: new Date("2026-03-02T10:00:00Z"),
  },
  {
    _id: "p3",
    facility_id: "f3",
    utility_account_id: "ua3",
    pump_tag_number: "P-HOT-1",
    make_model: "Crompton Booster Pump",
    rated_power_kW_or_HP: 7.5,
    rated_flow_m3_per_hr: 28,
    rated_head_m: 24,
    rated_speed_RPM: 2900,
    number_of_stages: 3,
    year_of_installation: 2020,
    created_at: new Date("2026-02-04T10:00:00Z"),
    updated_at: new Date("2026-03-03T10:00:00Z"),
  },
];

export const pump_audit_records: PumpAuditRecord[] = [
  {
    _id: "par1",
    pump_id: "p1",
    utility_account_id: "ua1",
    suction_head_m: 2.5,
    discharge_static_head_m: 23,
    delivery_pipe_diameter_inches: 4,
    tank_or_sump_capacity: 50000,
    time_to_fill_tank_minutes: 48,
    actual_flow_m3_per_hr: 62.5,
    voltage_V: 415,
    current_A: 26,
    power_factor: 0.88,
    input_power_kW: 14.2,
    operating_hours_per_day: 12,
    daily_energy_consumption_kWh: 170.4,
    total_dynamic_head_m: 27.4,
    hydraulic_output_power_kW: 4.67,
    overall_pump_set_efficiency_percent: 32.89,
    motor_loading_percent: 94.67,
    specific_energy_consumption_kWh_per_m3: 0.2272,
    annual_energy_consumption_kWh: 51120,
    control_valve_throttling: true,
    vfd_installed: false,
    pump_condition: "Fair",
    leakages_observed: false,
    recommendations: "Consider VFD and impeller trimming study",
    created_at: new Date("2026-03-01T19:00:00Z"),
    updated_at: new Date("2026-03-01T19:00:00Z"),
  },
  {
    _id: "par2",
    pump_id: "p2",
    utility_account_id: "ua2",
    suction_head_m: 1.8,
    discharge_static_head_m: 29,
    delivery_pipe_diameter_inches: 3,
    tank_or_sump_capacity: 30000,
    time_to_fill_tank_minutes: 43,
    actual_flow_m3_per_hr: 41.86,
    voltage_V: 415,
    current_A: 17.5,
    power_factor: 0.9,
    input_power_kW: 9.8,
    operating_hours_per_day: 18,
    daily_energy_consumption_kWh: 176.4,
    total_dynamic_head_m: 31.5,
    hydraulic_output_power_kW: 3.59,
    overall_pump_set_efficiency_percent: 36.63,
    motor_loading_percent: 98,
    specific_energy_consumption_kWh_per_m3: 0.2341,
    annual_energy_consumption_kWh: 64386,
    control_valve_throttling: false,
    vfd_installed: true,
    pump_condition: "Good",
    leakages_observed: false,
    recommendations: "Maintain current operation and monitor VFD settings",
    created_at: new Date("2026-03-02T19:00:00Z"),
    updated_at: new Date("2026-03-02T19:00:00Z"),
  },
  {
    _id: "par3",
    pump_id: "p3",
    utility_account_id: "ua3",
    suction_head_m: 1.2,
    discharge_static_head_m: 20,
    delivery_pipe_diameter_inches: 2.5,
    tank_or_sump_capacity: 12000,
    time_to_fill_tank_minutes: 28,
    actual_flow_m3_per_hr: 25.71,
    voltage_V: 415,
    current_A: 13.2,
    power_factor: 0.86,
    input_power_kW: 6.9,
    operating_hours_per_day: 10,
    daily_energy_consumption_kWh: 69,
    total_dynamic_head_m: 22.4,
    hydraulic_output_power_kW: 1.57,
    overall_pump_set_efficiency_percent: 22.75,
    motor_loading_percent: 92,
    specific_energy_consumption_kWh_per_m3: 0.2684,
    annual_energy_consumption_kWh: 22770,
    control_valve_throttling: true,
    vfd_installed: false,
    pump_condition: "Needs Maintenance",
    leakages_observed: true,
    recommendations: "Repair leakage and check pump alignment",
    created_at: new Date("2026-03-03T19:00:00Z"),
    updated_at: new Date("2026-03-03T19:00:00Z"),
  },
];

