import type { Company } from "@/store/slices/companyApiSlice";
import type { Expense } from "@/store/slices/expenseManagerApiSlice";
import { DEFAULT_PRIMARY_COLOR, companyLogoSrc } from "@/components/portal/lib/companyBranding";
import {
  COMPACT_HEADER_BOTTOM,
  LANDSCAPE_PAGE_LAYOUT,
  MUTED,
  NAVY,
  PORTRAIT_PAGE_LAYOUT,
  RULE,
  buildCompanyLetterhead,
  drawCompactHeader,
  drawFooter,
  drawFullLetterhead,
  formatPdfDate,
  formatPdfDateTime,
  hexToRgb,
  lighten,
  loadLogo,
  measureFooterHeight,
  type JsPdfDoc,
  type PdfPageLayout,
} from "@/components/portal/lib/letterheadPdf";

export type ExpenseReportPdfInput = {
  expenses: Expense[];
  company?: Company | null;
  logoSrc?: string;
  brandName?: string;
  primaryColor?: string;
  dateFrom?: string;
  dateTo?: string;
  teamFilterLabel?: string;
  memberFilterLabel?: string;
  statusFilterLabel?: string;
  categoryFilterLabel?: string;
  generatedBy?: string;
  orientation?: "portrait" | "landscape";
};

export function expenseReportPdfFilename() {
  const stamp = new Date().toISOString().split("T")[0];
  return `Expense_Claim_Report_${stamp}.pdf`;
}

function formatPdfMoney(amount: number | null | undefined): string {
  const num = Number(amount) || 0;
  return new Intl.NumberFormat("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(num);
}

export async function buildExpenseReportPdfBlob(
  input: ExpenseReportPdfInput
): Promise<Blob> {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const orientation = input.orientation || "landscape";
  const layout: PdfPageLayout = orientation === "landscape" ? LANDSCAPE_PAGE_LAYOUT : PORTRAIT_PAGE_LAYOUT;
  const primary = hexToRgb(input.primaryColor || DEFAULT_PRIMARY_COLOR);
  const headerBg = lighten(primary, 0.82);
  const letterhead = buildCompanyLetterhead(input.company, null, input.brandName);
  const logo = await loadLogo(input.logoSrc || companyLogoSrc(input.company));
  const exportedDateTime = formatPdfDateTime(new Date());

  let totalClaimed = 0;
  let approvedTotal = 0;
  input.expenses.forEach((e) => {
    const amt = Number(e.amount) || 0;
    totalClaimed += amt;
    if (e.status === "approved" || e.status === "reimbursed") {
      approvedTotal += amt;
    }
  });

  const filterBits: string[] = [];
  if (input.teamFilterLabel) filterBits.push(`Team: ${input.teamFilterLabel}`);
  if (input.memberFilterLabel) filterBits.push(`Member: ${input.memberFilterLabel}`);
  if (input.categoryFilterLabel) filterBits.push(`Category: ${input.categoryFilterLabel}`);
  if (input.statusFilterLabel) filterBits.push(`Status: ${input.statusFilterLabel}`);
  if (input.dateFrom || input.dateTo) {
    filterBits.push(`Date: ${input.dateFrom || "Start"} to ${input.dateTo || "End"}`);
  } else {
    filterBits.push(`Date: All Dates`);
  }
  const filterSummaryStr = `Filters Applied: ${filterBits.join("  |  ")}`;
  const compactSubtitle = `EXPENSE REPORT    ${filterSummaryStr}    Total: Rs. ${formatPdfMoney(totalClaimed)}`;
  const generatedByFooter = input.generatedBy
    ? `Generated by: ${input.generatedBy} on ${exportedDateTime}`
    : `Generated on ${exportedDateTime}`;

  const pdf = new jsPDF({
    orientation,
    unit: "mm",
    format: "a4",
  });
  const doc = pdf as unknown as JsPdfDoc;
  const footerH = measureFooterHeight(doc, letterhead, layout);
  const tableBottomMargin = footerH + 3;
  const tableMargins = {
    left: layout.marginX,
    right: layout.marginX,
    top: COMPACT_HEADER_BOTTOM,
    bottom: tableBottomMargin,
  };

  // Draw full letterhead on Page 1
  let y = drawFullLetterhead(doc, letterhead, logo, primary, layout);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...primary);
  doc.text("EXPENSE REIMBURSEMENT REPORT", layout.pageW / 2, y, { align: "center" });
  y += 4.5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(filterSummaryStr, layout.pageW / 2, y, { align: "center" });
  y += 4.5;

  const subtitleLine = `Total Claims: ${input.expenses.length} (Rs. ${formatPdfMoney(
    totalClaimed
  )})  •  Approved: Rs. ${formatPdfMoney(approvedTotal)}  •  ${generatedByFooter}`;
  doc.text(subtitleLine, layout.pageW / 2, y, { align: "center" });
  y += 6.5;

  // Render Table of Expenses
  const head = [["Employee & Role", "Date", "Category & Subcategory", "Amount (Rs.)", "Description", "Approved By", "Status"]];

  const body = input.expenses.map((e) => {
    const empInfo = `${e.employeeId?.name || "Employee"}\n(${e.employeeId?.role?.replace(/_/g, " ") || "Member"})`;
    const expDate = formatPdfDate(e.expenseDate);
    const catLabel = (e.category || "expense").replace(/_/g, " ").toUpperCase();
    const catSub = `${catLabel}${e.subcategory ? `\n- ${e.subcategory}` : ""}`;
    const amountStr = `Rs. ${formatPdfMoney(e.amount)}`;

    const approvedBy = e.approval?.approvedBy?.name
      ? `Approved by ${e.approval.approvedBy.name}`
      : e.approval?.rejectedBy?.name
      ? `Rejected by ${e.approval.rejectedBy.name}`
      : "Pending";

    const statusStr = (e.status || "pending").replace(/_/g, " ").toUpperCase();

    return [
      empInfo,
      expDate,
      catSub,
      amountStr,
      e.description || "-",
      approvedBy,
      statusStr,
    ];
  });

  autoTable(pdf, {
    startY: y,
    tableWidth: layout.contentW,
    margin: tableMargins,
    head,
    body,
    showHead: "everyPage",
    styles: {
      font: "helvetica",
      fontSize: 7.5,
      cellPadding: 2,
      overflow: "linebreak",
      valign: "top",
      lineColor: RULE,
      lineWidth: 0.2,
      textColor: NAVY,
    },
    headStyles: {
      fillColor: headerBg,
      textColor: NAVY,
      fontStyle: "bold",
      valign: "middle",
    },
    columnStyles: {
      0: { cellWidth: 36 },
      1: { cellWidth: 22 },
      2: { cellWidth: 34 },
      3: { cellWidth: 24, fontStyle: "bold", halign: "right" },
      4: { cellWidth: "auto" },
      5: { cellWidth: 32 },
      6: { cellWidth: 22 },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    willDrawPage: (data) => {
      if (data.pageNumber > 1) {
        doc.setPage(data.pageNumber);
        drawCompactHeader(doc, letterhead, compactSubtitle, logo, primary, layout);
      }
    },
  });

  const totalPages = doc.getNumberOfPages();
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    drawFooter(doc, letterhead, page, totalPages, primary, footerH, layout, generatedByFooter);
  }

  return doc.output("blob");
}
