import type {
  User,
  Facility,
  Connection,
  DGSystem,
  SolarSystem,
  AnalyticsData,
  TimeSeriesDataPoint,
  AuditSession,
  UtilityBillingRecord,
  SolarGenerationRecord,
  DGAuditRecord,
  TransformerAuditRecord,
  FanAuditRecord,
  LightingAuditRecord,
  LuxMeasurement,
  HVACAudit,
  MiscLoadAuditRecord,
  PumpAuditRecord,
} from "./types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Admin User",
    email: "admin@poweraudit.com",
    role: "admin",
    createdAt: "2024-01-15",
    lastActive: "2025-03-10",
  },
  {
    id: "user-2",
    name: "John Smith",
    email: "john.smith@poweraudit.com",
    role: "auditor",
    createdAt: "2024-02-20",
    lastActive: "2025-03-09",
  },
  {
    id: "user-3",
    name: "Sarah Johnson",
    email: "sarah.johnson@poweraudit.com",
    role: "auditor",
    createdAt: "2024-03-10",
    lastActive: "2025-03-10",
  },
  {
    id: "user-4",
    name: "Mike Wilson",
    email: "mike.wilson@poweraudit.com",
    role: "auditor",
    createdAt: "2024-04-05",
    lastActive: "2025-03-08",
  },
];

export const mockFacilities: Facility[] = [
  {
    id: "facility-1",
    name: "Metro Industrial Complex",
    address: "123 Industrial Way",
    city: "Chennai",
    state: "Tamil Nadu",
    zipCode: "600001",
    contactName: "Rajesh Kumar",
    contactEmail: "rajesh@metro-industrial.com",
    contactPhone: "+91 98765 43210",
    status: "completed",
    auditorId: "user-2",
    auditorName: "John Smith",
    createdAt: "2025-01-15",
    updatedAt: "2025-03-01",
    connectionCount: 5,
    totalCapacity: 2500,
  },
  {
    id: "facility-2",
    name: "Tech Park Towers",
    address: "456 IT Highway",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560001",
    contactName: "Priya Sharma",
    contactEmail: "priya@techpark.com",
    contactPhone: "+91 87654 32109",
    status: "in-progress",
    auditorId: "user-3",
    auditorName: "Sarah Johnson",
    createdAt: "2025-02-10",
    updatedAt: "2025-03-08",
    connectionCount: 8,
    totalCapacity: 4200,
  },
  {
    id: "facility-3",
    name: "Green Valley Mall",
    address: "789 Shopping Street",
    city: "Mumbai",
    state: "Maharashtra",
    zipCode: "400001",
    contactName: "Amit Patel",
    contactEmail: "amit@greenvalley.com",
    contactPhone: "+91 76543 21098",
    status: "pending",
    auditorId: "user-4",
    auditorName: "Mike Wilson",
    createdAt: "2025-03-05",
    updatedAt: "2025-03-05",
    connectionCount: 3,
    totalCapacity: 1800,
  },
  {
    id: "facility-4",
    name: "Sunrise Hospital",
    address: "321 Medical Lane",
    city: "Hyderabad",
    state: "Telangana",
    zipCode: "500001",
    contactName: "Dr. Suresh Reddy",
    contactEmail: "suresh@sunrisehospital.com",
    contactPhone: "+91 65432 10987",
    status: "approved",
    auditorId: "user-2",
    auditorName: "John Smith",
    createdAt: "2024-12-01",
    updatedAt: "2025-02-20",
    connectionCount: 6,
    totalCapacity: 3100,
  },
  {
    id: "facility-5",
    name: "Coastal Manufacturing Unit",
    address: "555 Port Road",
    city: "Vizag",
    state: "Andhra Pradesh",
    zipCode: "530001",
    contactName: "Venkat Rao",
    contactEmail: "venkat@coastalmfg.com",
    contactPhone: "+91 54321 09876",
    status: "in-progress",
    auditorId: "user-3",
    auditorName: "Sarah Johnson",
    createdAt: "2025-02-25",
    updatedAt: "2025-03-09",
    connectionCount: 4,
    totalCapacity: 5500,
  },
];

export const mockConnections: Connection[] = [
  {
    id: "conn-1",
    facilityId: "facility-1",
    name: "Main HT Connection",
    type: "HT",
    sanctionedLoad: 1000,
    contractDemand: 800,
    connectedLoad: 750,
    supplyVoltage: 11000,
    meterNumber: "HT-2024-001",
    accountNumber: "ACC-MIC-001",
    createdAt: "2025-01-15",
    updatedAt: "2025-02-20",
    dgCount: 2,
    solarCount: 1,
  },
  {
    id: "conn-2",
    facilityId: "facility-1",
    name: "Warehouse LT Connection",
    type: "LT",
    sanctionedLoad: 200,
    contractDemand: 150,
    connectedLoad: 140,
    supplyVoltage: 415,
    meterNumber: "LT-2024-002",
    accountNumber: "ACC-MIC-002",
    createdAt: "2025-01-16",
    updatedAt: "2025-02-21",
    dgCount: 1,
    solarCount: 0,
  },
  {
    id: "conn-3",
    facilityId: "facility-2",
    name: "Tower A Connection",
    type: "HT",
    sanctionedLoad: 1500,
    contractDemand: 1200,
    connectedLoad: 1100,
    supplyVoltage: 33000,
    meterNumber: "HT-2024-003",
    accountNumber: "ACC-TPT-001",
    createdAt: "2025-02-10",
    updatedAt: "2025-03-05",
    dgCount: 3,
    solarCount: 2,
  },
  {
    id: "conn-4",
    facilityId: "facility-2",
    name: "Tower B Connection",
    type: "HT",
    sanctionedLoad: 1500,
    contractDemand: 1200,
    connectedLoad: 1050,
    supplyVoltage: 33000,
    meterNumber: "HT-2024-004",
    accountNumber: "ACC-TPT-002",
    createdAt: "2025-02-11",
    updatedAt: "2025-03-06",
    dgCount: 2,
    solarCount: 2,
  },
  {
    id: "conn-5",
    facilityId: "facility-3",
    name: "Mall Main Connection",
    type: "HT",
    sanctionedLoad: 1800,
    contractDemand: 1500,
    connectedLoad: 1400,
    supplyVoltage: 11000,
    meterNumber: "HT-2024-005",
    accountNumber: "ACC-GVM-001",
    createdAt: "2025-03-05",
    updatedAt: "2025-03-05",
    dgCount: 4,
    solarCount: 1,
  },
];

export const mockDGSystems: DGSystem[] = [
  {
    id: "dg-1",
    connectionId: "conn-1",
    make: "Cummins",
    model: "C500D5",
    serialNumber: "CUM-2020-001",
    capacity: 500,
    fuelType: "Diesel",
    yearOfInstallation: 2020,
    runningHours: 2450,
    lastServiceDate: "2025-01-15",
    status: "operational",
  },
  {
    id: "dg-2",
    connectionId: "conn-1",
    make: "Kirloskar",
    model: "KG1-320",
    serialNumber: "KIR-2021-002",
    capacity: 320,
    fuelType: "Diesel",
    yearOfInstallation: 2021,
    runningHours: 1820,
    lastServiceDate: "2025-02-10",
    status: "operational",
  },
  {
    id: "dg-3",
    connectionId: "conn-2",
    make: "Mahindra",
    model: "MPG-125",
    serialNumber: "MAH-2022-001",
    capacity: 125,
    fuelType: "Diesel",
    yearOfInstallation: 2022,
    runningHours: 980,
    lastServiceDate: "2025-01-20",
    status: "operational",
  },
  {
    id: "dg-4",
    connectionId: "conn-3",
    make: "Caterpillar",
    model: "C15",
    serialNumber: "CAT-2019-001",
    capacity: 750,
    fuelType: "Diesel",
    yearOfInstallation: 2019,
    runningHours: 4200,
    lastServiceDate: "2024-12-15",
    status: "maintenance",
  },
  {
    id: "dg-5",
    connectionId: "conn-3",
    make: "Cummins",
    model: "QSK60-G3",
    serialNumber: "CUM-2021-003",
    capacity: 1000,
    fuelType: "Natural Gas",
    yearOfInstallation: 2021,
    runningHours: 2100,
    lastServiceDate: "2025-02-28",
    status: "operational",
  },
];

export const mockSolarSystems: SolarSystem[] = [
  {
    id: "solar-1",
    connectionId: "conn-1",
    panelMake: "Tata Solar",
    panelModel: "TP-400-M",
    panelCapacity: 400,
    numberOfPanels: 250,
    totalCapacity: 100,
    inverterMake: "ABB",
    inverterModel: "PVS-100",
    inverterCapacity: 100,
    inverterType: "Central",
    installationDate: "2023-06-15",
    status: "operational",
  },
  {
    id: "solar-2",
    connectionId: "conn-3",
    panelMake: "Vikram Solar",
    panelModel: "Eldora-445",
    panelCapacity: 445,
    numberOfPanels: 450,
    totalCapacity: 200,
    inverterMake: "SMA",
    inverterModel: "Sunny Tripower",
    inverterCapacity: 200,
    inverterType: "String",
    installationDate: "2024-01-20",
    status: "operational",
  },
  {
    id: "solar-3",
    connectionId: "conn-3",
    panelMake: "Adani Solar",
    panelModel: "AS-550",
    panelCapacity: 550,
    numberOfPanels: 180,
    totalCapacity: 100,
    inverterMake: "Fronius",
    inverterModel: "Symo 100",
    inverterCapacity: 100,
    inverterType: "String",
    installationDate: "2024-03-10",
    status: "operational",
  },
  {
    id: "solar-4",
    connectionId: "conn-4",
    panelMake: "Waaree",
    panelModel: "WS-540",
    panelCapacity: 540,
    numberOfPanels: 370,
    totalCapacity: 200,
    inverterMake: "Huawei",
    inverterModel: "SUN2000-185KTL",
    inverterCapacity: 185,
    inverterType: "String",
    installationDate: "2024-05-25",
    status: "operational",
  },
];

export const mockAnalytics: AnalyticsData = {
  totalFacilities: 5,
  totalConnections: 26,
  totalDGSystems: 18,
  totalSolarSystems: 12,
  completedAudits: 2,
  pendingAudits: 3,
  totalCapacity: 17100,
  solarCapacity: 600,
  dgCapacity: 2695,
};

export const mockTimeSeriesData: TimeSeriesDataPoint[] = [
  { date: "Jan", audits: 8, capacity: 12500 },
  { date: "Feb", audits: 12, capacity: 14200 },
  { date: "Mar", audits: 10, capacity: 15100 },
  { date: "Apr", audits: 15, capacity: 16800 },
  { date: "May", audits: 18, capacity: 17500 },
  { date: "Jun", audits: 14, capacity: 18200 },
  { date: "Jul", audits: 20, capacity: 19100 },
  { date: "Aug", audits: 22, capacity: 20500 },
  { date: "Sep", audits: 19, capacity: 21200 },
  { date: "Oct", audits: 25, capacity: 22800 },
  { date: "Nov", audits: 28, capacity: 24100 },
  { date: "Dec", audits: 30, capacity: 25500 },
];

export const recentActivity = [
  {
    id: "activity-1",
    action: "Audit completed",
    facility: "Metro Industrial Complex",
    user: "John Smith",
    timestamp: "2 hours ago",
  },
  {
    id: "activity-2",
    action: "New facility added",
    facility: "Green Valley Mall",
    user: "Mike Wilson",
    timestamp: "5 hours ago",
  },
  {
    id: "activity-3",
    action: "DG System added",
    facility: "Tech Park Towers",
    user: "Sarah Johnson",
    timestamp: "1 day ago",
  },
  {
    id: "activity-4",
    action: "Solar System installed",
    facility: "Sunrise Hospital",
    user: "John Smith",
    timestamp: "2 days ago",
  },
  {
    id: "activity-5",
    action: "Connection updated",
    facility: "Coastal Manufacturing",
    user: "Sarah Johnson",
    timestamp: "3 days ago",
  },
];

export const mockAuditSessions: AuditSession[] = [
  {
    id: "as-1",
    auditId: "audit-101",
    facilityId: "facility-1",
    connectionId: "conn-1",
    auditName: "March Energy Audit",
    auditDate: "2026-03-10",
    auditorName: "Ajit Kumar",
    status: "in-progress",
  },
  {
    id: "as-2",
    auditId: "audit-102",
    facilityId: "facility-1",
    connectionId: "conn-1",
    auditName: "Load Efficiency Audit",
    auditDate: "2026-03-11",
    auditorName: "Ajit Kumar",
    status: "completed",
  },
];

export const mockUtilityBillingRecords: UtilityBillingRecord[] = [
  {
    id: "ub-1",
    auditId: "audit-101",
    billingMonth: "Jan 2026",
    unitsConsumed: 12500,
    billingAmount: 98500,
    maxDemand: 320,
    powerFactor: 0.98,
  },
  {
    id: "ub-2",
    auditId: "audit-101",
    billingMonth: "Feb 2026",
    unitsConsumed: 11800,
    billingAmount: 93400,
    maxDemand: 305,
    powerFactor: 0.97,
  },
];

export const mockSolarGenerationRecords: SolarGenerationRecord[] = [
  {
    id: "sg-1",
    auditId: "audit-101",
    date: "2026-03-01",
    generation: 540,
    exportedEnergy: 120,
    remarks: "Normal generation",
  },
];

export const mockDGAuditRecords: DGAuditRecord[] = [
  {
    id: "dg-audit-1",
    auditId: "audit-101",
    dgName: "DG-1 Cummins",
    capacity: 500,
    fuelType: "Diesel",
    runningHours: 1280,
    status: "active",
  },
];

export const mockTransformerAuditRecords: TransformerAuditRecord[] = [
  {
    id: "tr-1",
    auditId: "audit-101",
    transformerName: "TR-1",
    capacity: 1000,
    voltageLevel: "11kV/433V",
    loadingPercent: 76,
    status: "normal",
  },
];

export const mockFanAuditRecords: FanAuditRecord[] = [
  {
    id: "fan-1",
    auditId: "audit-101",
    fanTag: "FAN-A1",
    location: "Admin Block",
    ratedPower: 75,
    quantity: 12,
    workingHoursPerDay: 10,
  },
];

export const mockLightingAuditRecords: LightingAuditRecord[] = [
  {
    id: "light-1",
    auditId: "audit-101",
    fixtureTag: "LT-01",
    location: "Office Hall",
    lampType: "LED Panel",
    wattage: 36,
    quantity: 20,
  },
];

export const mockLuxMeasurements: LuxMeasurement[] = [
  {
    id: "lux-1",
    auditId: "audit-101",
    areaLocation: "Office Hall",
    roomType: "Office",
    requiredLux: 300,
    measuredLuxPoint1: 280,
    measuredLuxPoint2: 295,
    measuredLuxPoint3: 290,
    averageLux: 288,
    compliance: "No",
    remarks: "Below recommended level",
  },
];

export const mockHVACAudits: HVACAudit[] = [
  {
    id: "hvac-1",
    auditId: "audit-101",
    equipmentName: "AHU-1",
    equipmentType: "Air Handling Unit",
    capacityTR: 20,
    powerConsumption: 8.5,
    status: "running",
  },
];

export const mockMiscLoadAuditRecords: MiscLoadAuditRecord[] = [
  {
    id: "misc-1",
    auditId: "audit-101",
    equipmentName: "Water Cooler",
    location: "Cafeteria",
    connectedLoad: 1.2,
    workingHoursPerDay: 8,
    remarks: "Operational",
  },
];

export const mockPumpAuditRecords: PumpAuditRecord[] = [
  {
    id: "pump-1",
    auditId: "audit-101",
    pumpName: "Pump-1",
    location: "Basement",
    motorCapacity: 7.5,
    flowRate: "120 LPM",
    status: "running",
  },
];