import type { Company } from "@/store/slices/companyApiSlice";
import type { WorkPlan, VisitItem, WorkItem } from "@/store/slices/workPlannerApiSlice";
import { DEFAULT_PRIMARY_COLOR, companyLogoSrc } from "@/components/portal/lib/companyBranding";
import {
  COMPACT_HEADER_BOTTOM,
  LANDSCAPE_PAGE_LAYOUT,
  MUTED,
  NAVY,
  PORTRAIT_PAGE_LAYOUT,
  RULE,
  buildCompanyLetterhead,
  drawCompactHeader,
  drawFooter,
  drawFullLetterhead,
  formatPdfDate,
  formatPdfDateTime,
  hexToRgb,
  lighten,
  loadLogo,
  measureFooterHeight,
  type JsPdfDoc,
  type PdfPageLayout,
} from "@/components/portal/lib/letterheadPdf";

export type WorkPlanReportPdfInput = {
  plans: WorkPlan[];
  company?: Company | null;
  logoSrc?: string;
  brandName?: string;
  primaryColor?: string;
  dateFrom?: string;
  dateTo?: string;
  teamFilterLabel?: string;
  memberFilterLabel?: string;
  statusFilterLabel?: string;
  planTypeFilterLabel?: string;
  generatedBy?: string;
  orientation?: "portrait" | "landscape";
};

export function workPlanReportPdfFilename() {
  const stamp = new Date().toISOString().split("T")[0];
  return `Work_Plan_Report_${stamp}.pdf`;
}

export async function buildWorkPlanReportPdfBlob(
  input: WorkPlanReportPdfInput
): Promise<Blob> {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const orientation = input.orientation || "landscape";
  const layout: PdfPageLayout = orientation === "landscape" ? LANDSCAPE_PAGE_LAYOUT : PORTRAIT_PAGE_LAYOUT;
  const primary = hexToRgb(input.primaryColor || DEFAULT_PRIMARY_COLOR);
  const headerBg = lighten(primary, 0.82);
  const letterhead = buildCompanyLetterhead(input.company, null, input.brandName);
  const logo = await loadLogo(input.logoSrc || companyLogoSrc(input.company));
  const exportedDateTime = formatPdfDateTime(new Date());

  const filterBits: string[] = [];
  if (input.teamFilterLabel) filterBits.push(`Team: ${input.teamFilterLabel}`);
  if (input.memberFilterLabel) filterBits.push(`Member: ${input.memberFilterLabel}`);
  if (input.statusFilterLabel) filterBits.push(`Status: ${input.statusFilterLabel}`);
  if (input.planTypeFilterLabel) filterBits.push(`Type: ${input.planTypeFilterLabel}`);
  if (input.dateFrom || input.dateTo) {
    filterBits.push(`Date: ${input.dateFrom || "Start"} to ${input.dateTo || "End"}`);
  } else {
    filterBits.push(`Date: All Dates`);
  }
  const filterSummaryStr = `Filters Applied: ${filterBits.join("  |  ")}`;
  const compactSubtitle = `WORK PLAN REPORT    ${filterSummaryStr}    Total: ${input.plans.length}`;
  const generatedByFooter = input.generatedBy
    ? `Generated by: ${input.generatedBy} on ${exportedDateTime}`
    : `Generated on ${exportedDateTime}`;

  const pdf = new jsPDF({
    orientation,
    unit: "mm",
    format: "a4",
  });
  const doc = pdf as unknown as JsPdfDoc;
  const footerH = measureFooterHeight(doc, letterhead, layout);
  const tableBottomMargin = footerH + 3;
  const tableMargins = {
    left: layout.marginX,
    right: layout.marginX,
    top: COMPACT_HEADER_BOTTOM,
    bottom: tableBottomMargin,
  };

  // Draw full company letterhead on Page 1
  let y = drawFullLetterhead(doc, letterhead, logo, primary, layout);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...primary);
  doc.text("WORK PLAN REPORT", layout.pageW / 2, y, { align: "center" });
  y += 4.5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(filterSummaryStr, layout.pageW / 2, y, { align: "center" });
  y += 4.5;

  const subtitleLine = `Total Work Plans: ${input.plans.length}  •  ${generatedByFooter}`;
  doc.text(subtitleLine, layout.pageW / 2, y, { align: "center" });
  y += 6.5;

  // Render Table of Work Plans
  const head = [["Plan Title & Type", "Owner & Role", "Date", "Approved By", "Status", "Site Visits & Tasks Details"]];

  const body = input.plans.map((p) => {
    const ownerInfo = `${p.owner?.name || "Employee"}\n(${p.owner?.role?.replace("_", " ") || "Member"})`;
    const planDate = formatPdfDate(p.date || p.period?.startDate);
    const approvedBy = p.approval?.approvedBy?.name
      ? `Approved by ${p.approval.approvedBy.name}`
      : p.status === "rejected"
      ? `Rejected: ${p.approval?.rejectionReason || "-"}`
      : "Pending";

    const visitsText = (p.visits || [])
      .map(
        (v, i) =>
          `Visit ${i + 1}: ${v.facilityName || v.facility?.name || v.clientName || "Site Visit"} [${v.status || "scheduled"}] ${
            v.purpose ? `- ${v.purpose}` : ""
          } ${v.notes ? `(Remarks: ${v.notes})` : ""}`
      )
      .join("\n");

    const tasksText = (p.works || [])
      .map((w, i) => `Task ${i + 1}: ${w.title || "Task"} [${w.status || "pending"}] ${w.notes ? `(Remarks: ${w.notes})` : ""}`)
      .join("\n");

    const detailsText = [visitsText && `VISITS:\n${visitsText}`, tasksText && `TASKS:\n${tasksText}`]
      .filter(Boolean)
      .join("\n\n") || "No items listed";

    const typeStr = (p.planType || "general").replace(/_/g, " ").toUpperCase();
    const statusStr = (p.status || "pending").replace(/_/g, " ").toUpperCase();

    return [
      `${p.title || "Work Plan"}\nType: ${typeStr}`,
      ownerInfo,
      planDate,
      approvedBy,
      statusStr,
      detailsText,
    ];
  });

  autoTable(pdf, {
    startY: y,
    tableWidth: layout.contentW,
    margin: tableMargins,
    head,
    body,
    showHead: "everyPage",
    styles: {
      font: "helvetica",
      fontSize: 7,
      cellPadding: 2,
      overflow: "linebreak",
      valign: "top",
      lineColor: RULE,
      lineWidth: 0.2,
      textColor: NAVY,
    },
    headStyles: {
      fillColor: headerBg,
      textColor: NAVY,
      fontStyle: "bold",
      valign: "middle",
    },
    columnStyles: {
      0: { cellWidth: 38 },
      1: { cellWidth: 32 },
      2: { cellWidth: 22 },
      3: { cellWidth: 30 },
      4: { cellWidth: 22 },
      5: { cellWidth: "auto" },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    willDrawPage: (data) => {
      if (data.pageNumber > 1) {
        doc.setPage(data.pageNumber);
        drawCompactHeader(doc, letterhead, compactSubtitle, logo, primary, layout);
      }
    },
  });

  const totalPages = doc.getNumberOfPages();
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    drawFooter(doc, letterhead, page, totalPages, primary, footerH, layout, generatedByFooter);
  }

  return doc.output("blob");
}
